In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd


df_main = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/취업활동통계등록부_증감율_정리.xlsx")
df_employ = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/분기별_지역별_산업_요약_증감율_정리.xlsx")

In [ ]:
df_main.head()
df_main.isna().sum()

sido              0
BR_GI_MCLS_CD     0
base_year         0
n_people          0
avg_age           0
med_age           0
avg_income       59
med_income       59
dtype: int64

In [ ]:
df_employ.head()
df_employ.isna().sum()

LocName                         0
ENT_LVL2                        0
base_year                       0
n_ent                           0
avg_ent_wker                  422
med_ent_wker                  422
avg_ent_sls                   125
med_ent_sls                   125
avg_ent_tdwrkr                422
med_ent_tdwrkr                422
avg_ONLINE_SLSA_RQST_NOCS    4249
med_ONLINE_SLSA_RQST_NOCS    4249
avg_ONLINE_SLSA_RQST_AMT     4249
med_ONLINE_SLSA_RQST_AMT     4249
avg_ONLINE_STLA_RQST_NOCS    3830
med_ONLINE_STLA_RQST_NOCS    3830
avg_ONLINE_STLA_RQST_AMT     3830
med_ONLINE_STLA_RQST_AMT     3830
dtype: int64

In [ ]:
sido_map = {
    "광주": "광주광역시",
    "대구": "대구광역시",
    "대전": "대전광역시",
    "부산": "부산광역시",
    "서울": "서울특별시",
    "세종": "세종특별자치시",
    "울산": "울산광역시",
    "인천": "인천광역시",
    "제주도": "제주특별자치도"
}


df_main['sido'] = df_main['sido'].replace(sido_map)

In [ ]:
import pandas as pd


df_employ["year"] = df_employ["base_year"].astype(str).str[:4].astype(int)


df_employ.rename(columns={"LocName": "sido", "ENT_LVL2": "industry_code"}, inplace=True)
df_main.rename(columns={"BR_GI_MCLS_CD": "industry_code"}, inplace=True)


df_merged = pd.merge(
    df_employ,
    df_main,
    left_on=["sido", "industry_code", "year"],
    right_on=["sido", "industry_code", "base_year"],
    how="left"
)


print(df_merged.head())

  sido  industry_code  base_year_x n_ent avg_ent_wker med_ent_wker  \
0  강원도              1        20184  2562            5            2
1  강원도              2        20184   598     7.581081            5
2  강원도              3        20184  2381     3.858586            3
3  강원도              5        20184    14   229.666667           37
4  강원도              6        20184    18    24.857143            4

   avg_ent_sls med_ent_sls avg_ent_tdwrkr med_ent_tdwrkr  ...  \
0   407.748148          42       2.138021              1  ...
1   489.866126         220       4.081081              2  ...
2    150.50924          60       2.484848            1.5  ...
3     22250.75      1292.5             13              5  ...
4  2330.714286         5.5      10.428571              1  ...

  med_ONLINE_STLA_RQST_NOCS avg_ONLINE_STLA_RQST_AMT med_ONLINE_STLA_RQST_AMT  \
0                         5                35.111111                        1
1                       336                12.333333                       13
2                      37.5                     3.75                        4
3                       NaN                      NaN                      NaN
4                       NaN                      NaN                      NaN

   year base_year_y n_people    avg_age med_age       avg_income  med_income
0  2018      2018.0     3712   49.71444      52  28149411.848458    19600000
1  2018      2018.0     5157  56.488656      59  13711621.173677     8273495
2  2018      2018.0     2891  56.396057      59  18470012.173971    12300000
3  2018      2018.0     2450  51.972653      54  54474954.455038    55833415
4  2018      2018.0      154  52.753247      55  31611342.404412    33722826

[5 rows x 25 columns]

In [ ]:
print("sido mismatch:")
print(set(df_employ['sido'].unique()) - set(df_main['sido'].unique()))
print(set(df_main['sido'].unique()) - set(df_employ['sido'].unique()))

sido mismatch:
set()
set()

In [ ]:
print("industry_code mismatch:")
print(set(df_employ['industry_code'].unique()) - set(df_main['industry_code'].unique()))
print(set(df_main['industry_code'].unique()) - set(df_employ['industry_code'].unique()))

industry_code mismatch:
set()
{np.int64(69)}

In [ ]:
print("year mismatch:")
print(set(df_employ['year'].unique()) - set(df_main['base_year'].unique()))
print(set(df_main['base_year'].unique()) - set(df_employ['year'].unique()))

year mismatch:
{np.int64(2024)}
set()

In [ ]:
# 각 데이터프레임에서 sido의 고유값 확인
print("✅ df_employ['sido'] unique values:")
print(df_employ['sido'].unique())

print("\n✅ df_main['sido'] unique values:")
print(df_main['sido'].unique())

✅ df_employ['sido'] unique values:
['강원도' '경기도' '경상남도' '경상북도' '광주광역시' '대구광역시' '대전광역시' '부산광역시' '서울특별시'
 '세종특별자치시' '울산광역시' '인천광역시' '전라남도' '전라북도' '제주특별자치도' '충청남도' '충청북도']

✅ df_main['sido'] unique values:
['강원도' '경기도' '경상남도' '경상북도' '광주광역시' '대구광역시' '대전광역시' '부산광역시' '서울특별시'
 '세종특별자치시' '울산광역시' '인천광역시' '전라남도' '전라북도' '제주특별자치도' '충청남도' '충청북도']

In [ ]:
df_merged.isna().sum()

sido                            0
industry_code                   0
base_year_x                     0
n_ent                           0
avg_ent_wker                  422
med_ent_wker                  422
avg_ent_sls                   125
med_ent_sls                   125
avg_ent_tdwrkr                422
med_ent_tdwrkr                422
avg_ONLINE_SLSA_RQST_NOCS    4249
med_ONLINE_SLSA_RQST_NOCS    4249
avg_ONLINE_SLSA_RQST_AMT     4249
med_ONLINE_SLSA_RQST_AMT     4249
avg_ONLINE_STLA_RQST_NOCS    3830
med_ONLINE_STLA_RQST_NOCS    3830
avg_ONLINE_STLA_RQST_AMT     3830
med_ONLINE_STLA_RQST_AMT     3830
year                            0
base_year_y                  3799
n_people                     3799
avg_age                      3799
med_age                      3799
avg_income                   3943
med_income                   3943
dtype: int64

In [ ]:
df_merged['industry_code'].unique()

array([ 1,  2,  3,  5,  6,  7,  8, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 41, 42, 45, 46, 47, 49, 50, 51, 52, 55, 56, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 68, 70, 71, 72, 73, 74, 75, 76, 84, 85, 86, 87,
       90, 91, 94, 95, 96, 97, 12, 99])

In [ ]:
df_산출량지수 = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/산출량지수.xlsx")
df_산출량지수.head()

,한국표준산업분류(KSIC 9차),2018.75,2019,2019.25,2019.5,2019.75,2020,2020.25,2020.5,2020.75,...,2022.5,2022.75,2023,2023.25,2023.5,2023.75,2024,2024.25,2024.5,2024.75
0,ALL 비농전산업,99.6,104.2,96.8,101.9,100.5,106.4,98.1,97.5,99,...,111.9,109.3,114.9,107.4,112.3,111.6,118.1,110.9,115,111.9
1,B 광업,103.7,109.1,89,114.9,95.7,106.3,88.2,108.8,92.1,...,101.6,94.6,97.5,81.4,100.1,83.5,96.4,79.2,91.1,73.2
2,+ C 제조업,99.1,103.4,93.5,101,99.9,106.3,96.9,95.5,100.7,...,114.2,107.1,107.7,100.8,107.2,106.8,113.3,106.6,112.9,109.2
3,C10 식료품 제조업,94,97.8,95.1,98.5,98.1,101.7,99.1,98.8,101.4,...,104.1,103.3,101.2,96.9,98.4,98,99.2,97.7,100.9,98.5
4,C11 음료 제조업,113.9,99.2,98.5,113.5,108.3,96.5,93.8,107.7,106.7,...,111.8,116.2,99.8,100.9,109.8,109.3,93.1,93.5,109.1,105.2

In [ ]:
import pandas as pd

# 매핑 테이블 불러오기
df_mapping = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/KSIC11_code_mapping.xlsx")

# 'KSIC11_중분류코드' 열 전처리: '~' → ',' 로 바꾸고, split
df_mapping['KSIC11_중분류코드'] = df_mapping['KSIC11_중분류코드'].astype(str).str.replace('~', ',')
df_mapping_expanded = df_mapping.assign(
    KSIC11_중분류코드=df_mapping['KSIC11_중분류코드'].str.split(',')
).explode('KSIC11_중분류코드')

# 공백 제거 및 숫자만 남기기
df_mapping_expanded['KSIC11_중분류코드'] = df_mapping_expanded['KSIC11_중분류코드'].str.strip()
df_mapping_expanded = df_mapping_expanded[df_mapping_expanded['KSIC11_중분류코드'].str.isnumeric()]
df_mapping_expanded['KSIC11_중분류코드'] = df_mapping_expanded['KSIC11_중분류코드'].astype(int)

In [ ]:
import pandas as pd

# 매핑 테이블 불러오기
df_mapping = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/KSIC11_code_mapping.xlsx")

# 'KSIC11_중분류코드' 열 전처리: '~' → ',' 로 바꾸고, split
df_mapping['KSIC11_중분류코드'] = df_mapping['KSIC11_중분류코드'].astype(str).str.replace('~', ',')
df_mapping_expanded = df_mapping.assign(
    KSIC11_중분류코드=df_mapping['KSIC11_중분류코드'].str.split(',')
).explode('KSIC11_중분류코드')

# 공백 제거 및 숫자만 남기기
df_mapping_expanded['KSIC11_중분류코드'] = df_mapping_expanded['KSIC11_중분류코드'].str.strip()
df_mapping_expanded = df_mapping_expanded[df_mapping_expanded['KSIC11_중분류코드'].str.isnumeric()]
df_mapping_expanded['KSIC11_중분류코드'] = df_mapping_expanded['KSIC11_중분류코드'].astype(int)


# 매칭 함수: industry_name 안에 원본 항목명이 포함되면 코드 매핑
def match_code(ind_name):
    match = df_mapping_expanded[
        df_mapping_expanded['원본_항목'].apply(lambda x: str(x) in str(ind_name))
    ]
    return match['KSIC11_중분류코드'].tolist() if not match.empty else None

# 산출량지수 데이터에 적용
df_산출량지수['industry_code'] = df_산출량지수['한국표준산업분류(KSIC 9차)'].apply(match_code)

# 코드가 여러 개인 경우 분해
df_산출량지수 = df_산출량지수.explode('industry_code')
df_산출량지수 = df_산출량지수[df_산출량지수['industry_code'].notna()]
df_산출량지수['industry_code'] = df_산출량지수['industry_code'].astype(int)

In [ ]:
df_산출량지수

,한국표준산업분류(KSIC 9차),2018.75,2019,2019.25,2019.5,2019.75,2020,2020.25,2020.5,2020.75,...,2022.75,2023,2023.25,2023.5,2023.75,2024,2024.25,2024.5,2024.75,industry_code
0,ALL 비농전산업,99.6,104.2,96.8,101.9,100.5,106.4,98.1,97.5,99,...,109.3,114.9,107.4,112.3,111.6,118.1,110.9,115,111.9,1
0,ALL 비농전산업,99.6,104.2,96.8,101.9,100.5,106.4,98.1,97.5,99,...,109.3,114.9,107.4,112.3,111.6,118.1,110.9,115,111.9,2
0,ALL 비농전산업,99.6,104.2,96.8,101.9,100.5,106.4,98.1,97.5,99,...,109.3,114.9,107.4,112.3,111.6,118.1,110.9,115,111.9,3
1,B 광업,103.7,109.1,89,114.9,95.7,106.3,88.2,108.8,92.1,...,94.6,97.5,81.4,100.1,83.5,96.4,79.2,91.1,73.2,5
1,B 광업,103.7,109.1,89,114.9,95.7,106.3,88.2,108.8,92.1,...,94.6,97.5,81.4,100.1,83.5,96.4,79.2,91.1,73.2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,R91 스포츠 및 오락관련 서비스업,163.2,152.3,140.7,168.6,160,156,100.8,98.1,101.9,...,169.7,150,130.7,173.7,166.3,155,133.5,175.2,164.1,91
75,"+ S 협회 및 단체, 수리 및 기타 개인 서비스업",107.2,118,104,110.4,104.3,117.3,92,98.1,97.5,...,106,123.9,102.8,107.6,109.6,126.3,101.6,107.4,106.5,80
76,S94 협회 및 단체,97.9,115.5,92,96.9,96.2,121.8,88.9,89.8,95,...,110,131.5,108.4,107.1,119.9,148.1,107.3,108,115.1,94
77,S95 수리업,107.6,102.3,90,100.6,104.2,101.5,87.8,102.2,107,...,109.1,107.5,94.5,104.7,108,104,91.2,101.3,105.4,95
78,S96 기타 개인서비스업,109,136.7,123,124.9,106.6,134.3,101.3,104.6,89.5,...,96.6,131.4,105,111.8,98.4,122.3,104.9,112.3,97.5,96

In [ ]:
df_merged

,sido,industry_code,base_year_x,n_ent,avg_ent_wker,med_ent_wker,avg_ent_sls,med_ent_sls,avg_ent_tdwrkr,med_ent_tdwrkr,...,med_ONLINE_STLA_RQST_NOCS,avg_ONLINE_STLA_RQST_AMT,med_ONLINE_STLA_RQST_AMT,year,base_year_y,n_people,avg_age,med_age,avg_income,med_income
0,강원도,1,20184,2562,5,2,407.748148,42,2.138021,1,...,5,35.111111,1,2018,2018.0,3712,49.71444,52,28149411.848458,19600000
1,강원도,2,20184,598,7.581081,5,489.866126,220,4.081081,2,...,336,12.333333,13,2018,2018.0,5157,56.488656,59,13711621.173677,8273495
2,강원도,3,20184,2381,3.858586,3,150.50924,60,2.484848,1.5,...,37.5,3.75,4,2018,2018.0,2891,56.396057,59,18470012.173971,12300000
3,강원도,5,20184,14,229.666667,37,22250.75,1292.5,13,5,...,NaN,NaN,NaN,2018,2018.0,2450,51.972653,54,54474954.455038,55833415
4,강원도,6,20184,18,24.857143,4,2330.714286,5.5,10.428571,1,...,NaN,NaN,NaN,2018,2018.0,154,52.753247,55,31611342.404412,33722826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29960,충청북도,94,20243,16467,14.619186,2,374.080808,17,7.111919,0,...,452,131.805556,73,2024,NaN,NaN,NaN,NaN,NaN,NaN
29961,충청북도,95,20243,3656,4.678521,2,226.563836,57,1.076814,0,...,8,7,1,2024,NaN,NaN,NaN,NaN,NaN,NaN
29962,충청북도,96,20243,9943,3.871747,1,62.655181,22,1.64684,1,...,9,6.315029,1,2024,NaN,NaN,NaN,NaN,NaN,NaN
29963,충청북도,97,20243,6,0,0,24.333333,29,0,0,...,NaN,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN
29964,충청북도,99,20243,*,*,*,*,*,*,*,...,*,*,*,2024,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_merged.isna().sum()

sido                            0
industry_code                   0
base_year_x                     0
n_ent                           0
avg_ent_wker                  422
med_ent_wker                  422
avg_ent_sls                   125
med_ent_sls                   125
avg_ent_tdwrkr                422
med_ent_tdwrkr                422
avg_ONLINE_SLSA_RQST_NOCS    4249
med_ONLINE_SLSA_RQST_NOCS    4249
avg_ONLINE_SLSA_RQST_AMT     4249
med_ONLINE_SLSA_RQST_AMT     4249
avg_ONLINE_STLA_RQST_NOCS    3830
med_ONLINE_STLA_RQST_NOCS    3830
avg_ONLINE_STLA_RQST_AMT     3830
med_ONLINE_STLA_RQST_AMT     3830
year                            0
base_year_y                  3799
n_people                     3799
avg_age                      3799
med_age                      3799
avg_income                   3943
med_income                   3943
dtype: int64

In [ ]:
import numpy as np

# industry_code 붙인 원본에서 melt
value_vars = [col for col in df_산출량지수.columns if isinstance(col, float) or isinstance(col, int)]

df_산출량지수_long = df_산출량지수.melt(
    id_vars=["한국표준산업분류(KSIC 9차)", "industry_code"],
    value_vars=value_vars,
    var_name="period",
    value_name="산출량지수"
).rename(columns={"한국표준산업분류(KSIC 9차)": "industry_name"})

def convert_period_to_base_year(period):
    # float 처리 보장
    period = float(period)
    year = int(period)
    decimal = round(period - year, 2)  # 소수점 이하 정밀도 보정

    # 정수 연도인 경우 → 전년도 4분기로 간주
    if decimal == 0:
        return (year - 1) * 10 + 4
    # 분기별 매핑
    quarter_map = {
        0.25: 1,
        0.5: 2,
        0.75: 3
    }
    quarter = quarter_map.get(decimal, 0)  # 잘못된 값이면 0 반환
    return year * 10 + quarter

df_산출량지수_long['base_year'] = df_산출량지수_long['period'].apply(convert_period_to_base_year)

In [ ]:
df_산출량지수_long.head(100)

                industry_name  industry_code   period  산출량지수  base_year
0                   ALL 비농전산업              1  2018.75   99.6      20183
1                   ALL 비농전산업              2  2018.75   99.6      20183
2                   ALL 비농전산업              3  2018.75   99.6      20183
3                        B 광업              5  2018.75  103.7      20183
4                        B 광업              6  2018.75  103.7      20183
..                        ...            ...      ...    ...        ...
95                C10 식료품 제조업             10     2019   97.8      20184
96                 C11 음료 제조업             11     2019   99.2      20184
97                 C12 담배 제조업             12     2019   85.3      20184
98        C13 섬유제품 제조업; 의복 제외             13     2019  120.3      20184
99  C14 의복, 의복액세서리 및 모피제품 제조업             14     2019  146.4      20184

[100 rows x 5 columns]

In [ ]:
df_merged.head(100)

,sido,industry_code,base_year_x,n_ent,avg_ent_wker,med_ent_wker,avg_ent_sls,med_ent_sls,avg_ent_tdwrkr,med_ent_tdwrkr,...,med_ONLINE_STLA_RQST_NOCS,avg_ONLINE_STLA_RQST_AMT,med_ONLINE_STLA_RQST_AMT,year,base_year_y,n_people,avg_age,med_age,avg_income,med_income
0,강원도,1,20184,2562,5,2,407.748148,42,2.138021,1,...,5,35.111111,1,2018,2018.0,3712,49.71444,52,28149411.848458,19600000
1,강원도,2,20184,598,7.581081,5,489.866126,220,4.081081,2,...,336,12.333333,13,2018,2018.0,5157,56.488656,59,13711621.173677,8273495
2,강원도,3,20184,2381,3.858586,3,150.50924,60,2.484848,1.5,...,37.5,3.75,4,2018,2018.0,2891,56.396057,59,18470012.173971,12300000
3,강원도,5,20184,14,229.666667,37,22250.75,1292.5,13,5,...,NaN,NaN,NaN,2018,2018.0,2450,51.972653,54,54474954.455038,55833415
4,강원도,6,20184,18,24.857143,4,2330.714286,5.5,10.428571,1,...,NaN,NaN,NaN,2018,2018.0,154,52.753247,55,31611342.404412,33722826
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,경기도,24,20184,3636,14.0019,5,6198.985658,681.5,3.488222,1,...,24,21.466667,6,2018,2018.0,38836,43.136703,43,42078049.540356,35084976
96,경기도,25,20184,29504,7.60202,4,1184.587754,314,2.329596,1,...,7,17.577381,2,2018,2018.0,165230,44.082945,45,34984603.296902,28330000
97,경기도,26,20184,13791,34.69734,4,21973.448829,360,5.827731,1,...,8,746.062745,2,2018,2018.0,290854,37.598768,37,69014141.947729,56397053.5
98,경기도,27,20184,5819,12.842595,4,2639.202293,371.5,3.205683,1,...,8,69.925134,4,2018,2018.0,59588,40.016211,39,41115388.357672,33262808
99,경기도,28,20184,13058,12.323537,4,3223.568119,311,3.056672,1,...,12,35.918519,2,2018,2018.0,110311,42.447335,43,38547741.924157,30400000

In [ ]:
df_merged = df_merged.merge(
    df_산출량지수_long[['industry_code', 'base_year', '산출량지수']],
    how='left',
    left_on=['industry_code', 'base_year_x'],
    right_on=['industry_code', 'base_year']
).drop(columns=['base_year'])  # 충돌 피함

# 매칭 실패 행 확인
df_failed_merge = df_merged[df_merged['산출량지수'].isna()]

# 몇 건인지 확인
print(f"매칭 실패 건수: {len(df_failed_merge)}")

# 실패한 industry_code, base_year_x 조합 예시
print(df_failed_merge[['industry_code', 'base_year_x']].drop_duplicates().head(10))

매칭 실패 건수: 0
Empty DataFrame
Columns: [industry_code, base_year_x]
Index: []

In [ ]:
df_노동생산지수 = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/산업생산 노동생산성지수.xlsx")
df_노동생산지수.head()

,한국표준산업분류(KSIC 9차),2019,2019.25,2019.5,2019.75,2020,2020.25,2020.5,2020.75,2021,...,2022.5,2022.75,2023,2023.25,2023.5,2023.75,2024,2024.25,2024.5,2024.75
0,ALL 비농전산업,110.3,101.6,106.1,104.6,110.2,96.8,97.8,99.5,106.1,...,107.1,104.4,109,100.7,105,104.4,110.1,101.8,104.3,100.8
1,B 광업,117.2,93.2,118.9,100.8,114.2,81.5,107.5,93.5,120.5,...,113.2,107.6,109.5,88.5,108.6,91.4,105.4,80.7,83.6,63.4
2,+ C 제조업,104,93,100.8,99.9,106.7,94.9,95.8,101.5,108.1,...,113.9,106.5,105.8,100.8,107.4,106.8,113.1,106.7,113.1,109.1
3,C10 식료품 제조업,100.4,97.4,100,98.9,100.2,98.6,100.7,101.1,99.7,...,98.5,96.7,93.4,89.7,90.9,89.7,89.6,88.8,91.7,89.6
4,C11 음료 제조업,101.2,99.6,113.4,106.3,94.1,90.9,106.8,107.4,95.1,...,113.7,117.1,100.2,100,107.6,107,91,91.9,107.2,104.3

In [ ]:
# 매칭 함수: industry_name 안에 원본 항목명이 포함되면 코드 매핑
def match_code(ind_name):
    match = df_mapping_expanded[
        df_mapping_expanded['원본_항목'].apply(lambda x: str(x) in str(ind_name))
    ]
    return match['KSIC11_중분류코드'].tolist() if not match.empty else None

# 노동생산지수 데이터에 적용
df_노동생산지수['industry_code'] = df_노동생산지수['한국표준산업분류(KSIC 9차)'].apply(match_code)

# 코드가 여러 개인 경우 분해
df_노동생산지수 = df_노동생산지수.explode('industry_code')
df_노동생산지수 = df_노동생산지수[df_노동생산지수['industry_code'].notna()]
df_노동생산지수['industry_code'] = df_노동생산지수['industry_code'].astype(int)


import numpy as np

# industry_code 붙인 원본에서 melt
value_vars = [col for col in df_노동생산지수.columns if isinstance(col, float) or isinstance(col, int)]

df_노동생산지수_long = df_노동생산지수.melt(
    id_vars=["한국표준산업분류(KSIC 9차)", "industry_code"],
    value_vars=value_vars,
    var_name="period",
    value_name="노동생산지수"
).rename(columns={"한국표준산업분류(KSIC 9차)": "industry_name"})

def convert_period_to_base_year(period):
    # float 처리 보장
    period = float(period)
    year = int(period)
    decimal = round(period - year, 2)  # 소수점 이하 정밀도 보정

    # 정수 연도인 경우 → 전년도 4분기로 간주
    if decimal == 0:
        return (year - 1) * 10 + 4
    # 분기별 매핑
    quarter_map = {
        0.25: 1,
        0.5: 2,
        0.75: 3
    }
    quarter = quarter_map.get(decimal, 0)  # 잘못된 값이면 0 반환
    return year * 10 + quarter

df_노동생산지수_long['base_year'] = df_노동생산지수_long['period'].apply(convert_period_to_base_year)

In [ ]:
df_merged

,sido,industry_code,base_year_x,n_ent,avg_ent_wker,med_ent_wker,avg_ent_sls,med_ent_sls,avg_ent_tdwrkr,med_ent_tdwrkr,...,avg_ONLINE_STLA_RQST_AMT,med_ONLINE_STLA_RQST_AMT,year,base_year_y,n_people,avg_age,med_age,avg_income,med_income,산출량지수
0,강원도,1,20184,2562,5,2,407.748148,42,2.138021,1,...,35.111111,1,2018,2018.0,3712,49.71444,52,28149411.848458,19600000,104.2
1,강원도,2,20184,598,7.581081,5,489.866126,220,4.081081,2,...,12.333333,13,2018,2018.0,5157,56.488656,59,13711621.173677,8273495,104.2
2,강원도,3,20184,2381,3.858586,3,150.50924,60,2.484848,1.5,...,3.75,4,2018,2018.0,2891,56.396057,59,18470012.173971,12300000,104.2
3,강원도,5,20184,14,229.666667,37,22250.75,1292.5,13,5,...,NaN,NaN,2018,2018.0,2450,51.972653,54,54474954.455038,55833415,109.1
4,강원도,6,20184,18,24.857143,4,2330.714286,5.5,10.428571,1,...,NaN,NaN,2018,2018.0,154,52.753247,55,31611342.404412,33722826,109.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29960,충청북도,94,20243,16467,14.619186,2,374.080808,17,7.111919,0,...,131.805556,73,2024,NaN,NaN,NaN,NaN,NaN,NaN,115.1
29961,충청북도,95,20243,3656,4.678521,2,226.563836,57,1.076814,0,...,7,1,2024,NaN,NaN,NaN,NaN,NaN,NaN,105.4
29962,충청북도,96,20243,9943,3.871747,1,62.655181,22,1.64684,1,...,6.315029,1,2024,NaN,NaN,NaN,NaN,NaN,NaN,97.5
29963,충청북도,97,20243,6,0,0,24.333333,29,0,0,...,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,115.6
29964,충청북도,99,20243,*,*,*,*,*,*,*,...,*,*,2024,NaN,NaN,NaN,NaN,NaN,NaN,115.6

In [ ]:
df_merged = df_merged.merge(
    df_노동생산지수_long[['industry_code', 'base_year', '노동생산지수']],
    how='left',
    left_on=['industry_code', 'base_year_x'],
    right_on=['industry_code', 'base_year']
).drop(columns=['base_year'])  # 충돌 피함

# 매칭 실패 행 확인
df_failed_merge = df_merged[df_merged['노동생산지수'].isna()]

# 몇 건인지 확인
print(f"매칭 실패 건수: {len(df_failed_merge)}")

# 실패한 industry_code, base_year_x 조합 예시
print(df_failed_merge[['industry_code', 'base_year_x']].drop_duplicates().head(10))

매칭 실패 건수: 0
Empty DataFrame
Columns: [industry_code, base_year_x]
Index: []

In [ ]:
df_merged.head()

,sido,industry_code,base_year_x,n_ent,avg_ent_wker,med_ent_wker,avg_ent_sls,med_ent_sls,avg_ent_tdwrkr,med_ent_tdwrkr,...,med_ONLINE_STLA_RQST_AMT,year,base_year_y,n_people,avg_age,med_age,avg_income,med_income,산출량지수,노동생산지수
0,강원도,1,20184,2562,5,2,407.748148,42,2.138021,1,...,1,2018,2018.0,3712,49.71444,52,28149411.848458,19600000,104.2,110.3
1,강원도,2,20184,598,7.581081,5,489.866126,220,4.081081,2,...,13,2018,2018.0,5157,56.488656,59,13711621.173677,8273495,104.2,110.3
2,강원도,3,20184,2381,3.858586,3,150.50924,60,2.484848,1.5,...,4,2018,2018.0,2891,56.396057,59,18470012.173971,12300000,104.2,110.3
3,강원도,5,20184,14,229.666667,37,22250.75,1292.5,13,5,...,NaN,2018,2018.0,2450,51.972653,54,54474954.455038,55833415,109.1,117.2
4,강원도,6,20184,18,24.857143,4,2330.714286,5.5,10.428571,1,...,NaN,2018,2018.0,154,52.753247,55,31611342.404412,33722826,109.1,117.2

In [ ]:
df_merged["산출량지수"] = pd.to_numeric(df_merged["산출량지수"], errors="coerce")
df_merged["노동생산지수"] = pd.to_numeric(df_merged["노동생산지수"], errors="coerce")

In [ ]:
df_부가가치 = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/부가가치.xlsx")
df_부가가치.head()

     연도               업종    명목부가가치
0  2018             농림어업  32098102
1  2018               광업   1997711
2  2018        음식료품 및 담배  24843492
3  2018          섬유 및 가죽  17707388
4  2018  목재, 종이, 인쇄 및 복제  15071496

In [ ]:
# 매핑 딕셔너리 정의
custom_mapping = {
    "농림어업": ["1", "2", "3"],
    "광업": ["5", "6", "7", "8"],
    "음식료품 및 담배": ["10", "11", "12"],
    "섬유 및 가죽": ["13", "14", "15"],
    "목재, 종이, 인쇄 및 복제": ["16", "17", "18"],
    "석탄 및 석유": ["19"],
    "화학물질 및 화학": ["20"],
    "의약품 및 의료물질": ["21"],
    "고무제품 및 플라스틱": ["22"],
    "비금속광물": ["23"],
    "1차금속": ["24"],
    "금속제품": ["25"],
    "전자부품": ["26"],
    "컴퓨터 및 주변기기": ["26"],
    "통신, 방송 및 영상, 음향기기": ["26"],
    "정밀기기": ["27"],
    "전기장비": ["28"],
    "기계 및 장비": ["29", '34'],
    "자동차": ["30"],
    "기타 운송장비": ["31"],
    "기타 제조업": ["32", '33'],
    "전기 가스 증기 및 공기조절 공급": ["35"],
    "수도, 폐기물 및 재활용서비스": ["36", "37", "38", "39"],
    "건설업": ["41", "42", "43"],
    "도매 및 소매": ["45", "46", "47"],
    "운수 및 보관": ["49", "50", "51", "52"],
    "음식점 및 숙박": ["55", "56"],
    "출판, 영화 및 방송": ["58", "59", "60"],
    "통신업": ["61"],
    "정보서비스": ["62", "63"],
    "금융 및 보험": ["64", "65", "66"],
    "부동산 및 임대": ["68", "76"],
    "전문,과학 및 기술서비스": ["69", "70", "71", "72","73"],
    "사업지원 서비스": ["74", "75"],
    "공공행정 및 국방": ["84", "99"],
    "교육서비스업": ["85"],
    "보건 및 사회복지": ["86", "87", "88"],
    "문화 및 기타서비스": ["90", "91", "92", "93", "94", "95", "96", "97", "98"]
}

# 업종 매핑
def map_custom_industry(name):
    return custom_mapping.get(name, None)

df_부가가치['industry_code'] = df_부가가치['업종'].apply(map_custom_industry)
df_부가가치 = df_부가가치.explode('industry_code')
df_부가가치 = df_부가가치[df_부가가치['industry_code'].notna()]
df_부가가치['industry_code'] = df_부가가치['industry_code'].astype(int)

In [ ]:
df_부가가치_grouped = df_부가가치.groupby(['연도', 'industry_code'], as_index=False)['명목부가가치'].sum()

In [ ]:
df_부가가치_expanded = pd.concat([
    pd.DataFrame({
        '연도': [row['연도']] * 4,
        'industry_code': [row['industry_code']] * 4,
        '명목부가가치': [row['명목부가가치']] * 4,
        'base_year': [row['연도'] * 10 + q for q in [1, 2, 3, 4]]
    })
    for _, row in df_부가가치_grouped.iterrows()
], ignore_index=True)

In [ ]:
df_부가가치_expanded.columns.tolist(), df_부가가치_expanded.shape

(['연도', 'industry_code', '명목부가가치', 'base_year'], (1968, 4))

In [ ]:
df_merged = df_merged.merge(
    df_부가가치_expanded[['industry_code', 'base_year', '명목부가가치']],
    how='left',
    left_on=['industry_code', 'base_year_x'],
    right_on=['industry_code', 'base_year']
).drop(columns=['base_year'])

In [ ]:
df_merged[df_merged['명목부가가치'].isna()][['industry_code', 'base_year_x']].drop_duplicates().head(1000)

       industry_code  base_year_x
26220              1        20241
26221              2        20241
26222              3        20241
26223              5        20241
26224              6        20241
...              ...          ...
28788             95        20243
28789             96        20243
28790             97        20243
28791             99        20243
28801             12        20243

[228 rows x 2 columns]

In [ ]:
# CSV로 저장
df_merged.to_csv('merged.csv', index=False, encoding='utf-8-sig')

In [ ]:
df_merged = pd.read_csv("/content/merged.csv")

In [ ]:
df_취업자 = pd.read_excel("/content/drive/MyDrive/디스커버/25-1/메인프로젝트/해야하는 폴더/산업별 취업자(성,시도,연령별).xlsx", header=1)
df_취업자.head()

,성별,행정구역별,연령별,항목,단위,2014. 1/2,2014. 2/2,2015. 1/2,2015. 2/2,2016. 1/2,...,2019. 2/2,2020. 1/2,2020. 2/2,2021. 1/2,2021. 2/2,2022. 1/2,2022. 2/2,2023. 1/2,2023. 2/2,2024. 1/2
0,전체,전국,계,합계,NaN,25834.60370,26099.03937,25991.48465,26346.01358,26156.19034,...,27346.83918,26397.32881,26916.90112,27213.59232,27740.74699,28078.30968,28417.86366,28432.06699,28763.87634,28693.42611
1,전체,전국,계,농림어업,NaN,1556.08159,1602.28053,1421.76187,1473.08248,1355.41571,...,1551.32599,1479.33688,1573.95216,1476.33225,1593.99323,1544.66108,1640.60640,1556.92265,1657.09336,1561.77966
2,전체,전국,계,광업,NaN,14.07833,8.68305,13.35277,15.39945,18.45547,...,14.85899,14.79954,10.5006,12.76848,10.66067,13.10791,6.12520,7.33179,7.56453,7.82779
3,전체,전국,계,제조업,NaN,4360.50622,4419.64827,4507.11464,4594.70838,4528.87763,...,4381.63380,4322.13703,4283.33287,4386.11068,4323.55863,4517.98609,4524.94367,4420.90769,4448.20282,4520.4714
4,전체,전국,계,"전기,가스,증기 및 수도사업",NaN,83.69547,86.08151,93.61092,96.97573,89.95810,...,88.89853,83.41409,93.8141,64.53602,76.66299,76.05670,84.03880,82.92196,94.98596,94.12442

In [ ]:
# 1. 반기 형식 (예: '2014. 1/2')만 추출
value_vars = [col for col in df_취업자.columns if isinstance(col, str) and '/' in col]

# 2. 긴 형식으로 변환 (melt)
df_취업자_long = df_취업자.melt(
    id_vars=['행정구역별', '연령별', '항목'],
    value_vars=value_vars,
    var_name='period',
    value_name='취업자수_천명'
)

In [ ]:
# 숫자형으로 변환
df_취업자_long['취업자수_천명'] = pd.to_numeric(df_취업자_long['취업자수_천명'], errors='coerce')

# '전국' 제거
df_취업자_long = df_취업자_long[df_취업자_long['행정구역별'] != '전국']

In [ ]:
df_취업자_집계 = df_취업자_long.groupby(['행정구역별', '항목', 'period'], as_index=False)['취업자수_천명'].sum()

In [ ]:
def convert_half_year_to_base_year(period_str):
    """
    예: '2018. 1/2' → [20181, 20182]
        '2018. 2/2' → [20183, 20184]
    """
    try:
        parts = period_str.replace(" ", "").split(".")
        year = int(parts[0])
        half = parts[1]

        if half == '1/2':
            return [year * 10 + 1, year * 10 + 2]
        elif half == '2/2':
            return [year * 10 + 3, year * 10 + 4]
        else:
            return []
    except Exception as e:
        print(f"[⚠️ 오류] '{period_str}' 파싱 실패: {e}")
        return []

# 확장
expanded_rows = []
for _, row in df_취업자_집계.iterrows():
    base_years = convert_half_year_to_base_year(row['period'])
    for base_year in base_years:
        expanded_rows.append({
            '지역': row['행정구역별'],
            'industry_name': row['항목'],
            'base_year': base_year,
            '취업자수_천명': row['취업자수_천명']
        })

df_취업자_expanded = pd.DataFrame(expanded_rows)

In [ ]:
# 예시 매핑 딕셔너리 (실제 건 너가 만든 걸 사용)
취업자_매핑 = {
    "농림어업": ["01", "02", "03"],
    "광업": ["05", "06", "07", "08"],
    "제조업": [
        "10", "11", "12", "13", "14", "15", "16", "17", "18",
        "19", "20", "21", "22", "23", "24", "25", "26", "27",
        "28", "29", "30", "31", "32", "33", "34"
    ],
    "전기,가스,증기 및 수도사업": ["35", "36"],
    "하수·폐기물처리,원료재생 및 환경복원업": ["37", "38", "39"],
    "건설업": ["41", "42", "43"],
    "도소매업": ["45", "46", "47"],
    "운수업": ["49", "50", "51", "52"],
    "숙박 및 음식점업": ["55", "56"],
    "출판,영상,방송통신 및 정보서비스업": ["58", "59", "60", "61", "62", "63"],
    "금융 및 보험업": ["64", "65", "66"],
    "부동산업 및 임대업": ["68", "76"],
    "전문,과학 및 기술서비스업": ["69", "70", "71", "72", "73"],
    "사업시설관리 및 사업지원 서비스업": ["74", "75"],
    "공공행정,국방 및 사회보장행정": ["84", "99"],
    "교육서비스업": ["85"],
    "보건업 및 사회복지서비스업": ["86", "87", "88"],
    "예술,스포츠 및 여가관련 서비스업": ["90", "91", "92", "93"],
    "협회 및 단체,수리 기타 개인서비스업": ["94", "95", "96"],
    "가구내 고용활동 및 달리 분류되지 않는 자가소비생산활동": ["97"],
    "국제 및 외국기관": ["98"]
}


# 매핑 딕셔너리는 이전에 사용한 것을 그대로 사용
df_취업자_expanded['industry_code'] = df_취업자_expanded['industry_name'].map(취업자_매핑)

# 리스트 형태를 행으로 분해
df_취업자_expanded = df_취업자_expanded.dropna(subset=['industry_code'])
df_취업자_expanded = df_취업자_expanded.explode('industry_code')
df_취업자_expanded['industry_code'] = df_취업자_expanded['industry_code'].astype(int)

In [ ]:
# 행정구역명 매핑: 취업자 데이터 기준 → df_merged 기준
지역명_매핑 = {
    "강원특별자치도": "강원도",
    "제주특별자치도": "제주특별자치도",  # 이미 동일
    # 나머지 지역은 동일하므로 생략 가능
}

# 매핑 적용
df_취업자_expanded['지역'] = df_취업자_expanded['지역'].replace(지역명_매핑)

In [ ]:
df_merged = df_merged.merge(
    df_취업자_expanded,
    how='left',
    left_on=['sido', 'industry_code', 'base_year_x'],
    right_on=['지역', 'industry_code', 'base_year']
)

In [ ]:
# 병합으로 생긴 base_year, 지역 컬럼 제거
df_merged = df_merged.drop(columns=['base_year', '지역'])

In [ ]:
# 매칭 실패 확인
df_fail = df_merged[df_merged['취업자수_천명'].isna()]
print(f"병합 실패 건수: {len(df_fail)}")
print(df_fail[['sido', 'industry_code', 'base_year_x']].drop_duplicates().head())

병합 실패 건수: 1248
      sido  industry_code  base_year_x
28717  강원도              1        20243
28718  강원도              2        20243
28719  강원도              3        20243
28720  강원도              5        20243
28721  강원도              6        20243

In [ ]:
df_merged = df_merged.drop(columns=[
    'year',
    'base_year_y',     # 병합 시 생긴 중복 base_year
    'industry_name_y',  # 병합된 industry_name (중복)
    "industry_name"
    ], errors='ignore')  # 해당 컬럼이 없더라도 에러 없이 진행

In [ ]:
df_merged = df_merged.rename(columns={
    '산출량지수': 'output_index',
    '노동생산지수': 'labor_productivity_index',
    '명목부가가치': 'nominal_value_added',
    '취업자수_천명': 'employment_thousand'
})

In [ ]:
# float 형 컬럼에 대해서만 반올림 적용
float_cols = df_merged.select_dtypes(include='number').columns
df_merged[float_cols] = df_merged[float_cols].round(2)

In [ ]:
df_merged.isna().sum()

sido                            0
industry_code                   0
base_year_x                     0
n_ent                           0
avg_ent_wker                  422
med_ent_wker                  422
avg_ent_sls                   125
med_ent_sls                   125
avg_ent_tdwrkr                422
med_ent_tdwrkr                422
avg_ONLINE_SLSA_RQST_NOCS    4249
med_ONLINE_SLSA_RQST_NOCS    4249
avg_ONLINE_SLSA_RQST_AMT     4249
med_ONLINE_SLSA_RQST_AMT     4249
avg_ONLINE_STLA_RQST_NOCS    3830
med_ONLINE_STLA_RQST_NOCS    3830
avg_ONLINE_STLA_RQST_AMT     3830
med_ONLINE_STLA_RQST_AMT     3830
n_people                     3799
avg_age                      3799
med_age                      3799
avg_income                   3943
med_income                   3943
output_index                  408
labor_productivity_index      408
nominal_value_added          3745
employment_thousand          1248
dtype: int64

In [ ]:
import numpy as np

# 1. "*"를 NaN으로 변환
df_merged = df_merged.replace("*", np.nan)


target_cols = ['avg_ent_wker','med_ent_wker','avg_ent_sls','med_ent_sls','avg_ent_tdwrkr','med_ent_tdwrkr','avg_ONLINE_SLSA_RQST_NOCS',
               'med_ONLINE_SLSA_RQST_NOCS','avg_ONLINE_SLSA_RQST_AMT','med_ONLINE_SLSA_RQST_AMT','avg_ONLINE_STLA_RQST_NOCS','med_ONLINE_STLA_RQST_NOCS','avg_ONLINE_STLA_RQST_AMT','med_ONLINE_STLA_RQST_AMT',
               'n_people','avg_age','med_age','avg_income','med_income']


# 2. 수치형으로 변환
for col in target_cols:
    if col in df_merged.columns:
        df_merged[col] = pd.to_numeric(df_merged[col], errors='coerce')

# 3. 같은 industry_code + base_year_x 단위의 평균으로 결측치 채우기
for col in target_cols:
    if col in df_merged.columns:
        df_merged[col] = df_merged.groupby(['industry_code', 'base_year_x'])[col].transform(
            lambda x: x.fillna(x.mean())
        )

In [ ]:
import random

# 'n_ent' 컬럼의 "*"를 NaN으로 변환
df_merged['n_ent'] = df_merged['n_ent'].replace("*", np.nan)

# NaN인 곳에 1 또는 2 랜덤값 채우기
df_merged['n_ent'] = df_merged['n_ent'].apply(
    lambda x: random.choice([1, 2]) if pd.isna(x) else x
)

# 타입을 정수형으로 변환 (선택적)
df_merged['n_ent'] = df_merged['n_ent'].astype(int)

In [ ]:
# CSV로 저장
df_merged.to_csv('final.csv', index=False, encoding='utf-8-sig')

In [ ]:
# 결측치 개수 및 비율
null_summary = df_merged.isna().sum().to_frame('null_count')
null_summary['null_ratio'] = null_summary['null_count'] / len(df_merged)
null_summary = null_summary[null_summary['null_count'] > 0].sort_values(by='null_count', ascending=False)

# 데이터 타입
dtypes = df_merged.dtypes.to_frame('dtype')

# 결합해서 보기 좋게
summary = null_summary.merge(dtypes, left_index=True, right_index=True)
print(summary)

                           null_count  null_ratio    dtype
med_age                          3745    0.124979  float64
avg_income                       3745    0.124979  float64
n_people                         3745    0.124979  float64
med_income                       3745    0.124979  float64
avg_age                          3745    0.124979  float64
nominal_value_added              3745    0.124979  float64
avg_ONLINE_SLSA_RQST_NOCS        1519    0.050692  float64
avg_ONLINE_SLSA_RQST_AMT         1519    0.050692  float64
med_ONLINE_SLSA_RQST_NOCS        1519    0.050692  float64
med_ONLINE_SLSA_RQST_AMT         1519    0.050692  float64
employment_thousand              1248    0.041649  float64
med_ONLINE_STLA_RQST_AMT         1091    0.036409  float64
avg_ONLINE_STLA_RQST_AMT         1091    0.036409  float64
med_ONLINE_STLA_RQST_NOCS        1091    0.036409  float64
avg_ONLINE_STLA_RQST_NOCS        1091    0.036409  float64
labor_productivity_index          408    0.013616  float64
output_index                      408    0.013616  float64
med_ent_sls                       162    0.005406  float64
avg_ent_sls                       162    0.005406  float64

In [ ]:
# object 타입 → float 변환 (필수!)
cols_to_numeric = summary[summary['dtype'] == 'object'].index.tolist()
df_merged[cols_to_numeric] = df_merged[cols_to_numeric].apply(pd.to_numeric, errors='coerce')

# 연도도 정수형으로 변환
df_merged['base_year_x'] = df_merged['base_year_x'].astype(int)

In [ ]:
# 정교한 보간 대상 변수들 (필요시 추가 가능)
target_cols = [
    'med_income',
'avg_income',
'avg_age',
'n_people',
'med_age',
    'nominal_value_added',
    'employment_thousand'
]

In [ ]:
# 산업, 지역, 연도 기준 정렬
df_merged = df_merged.sort_values(['industry_code', 'sido', 'base_year_x'])

# 보간 수행
for col in target_cols:
    if col in df_merged.columns:
        df_merged[col] = df_merged.groupby(['industry_code', 'sido'])[col].transform(
            lambda x: x.interpolate(method='linear', limit_direction='both')
        )

In [ ]:
df_merged[df_merged['output_index'].isna()]

,sido,industry_code,base_year_x,n_ent,avg_ent_wker,med_ent_wker,avg_ent_sls,med_ent_sls,avg_ent_tdwrkr,med_ent_tdwrkr,...,med_ONLINE_STLA_RQST_AMT,n_people,avg_age,med_age,avg_income,med_income,output_index,labor_productivity_index,nominal_value_added,employment_thousand
63,강원도,76,20184,1025,2.979167,2.0,145.028603,36.0,1.265625,1.0,...,1.0,2087.0,42.912793,43.0,2.110388e+07,17237916.0,NaN,NaN,159165824.0,44.26
1313,강원도,76,20191,926,3.160221,2.0,172.445609,46.0,1.342541,1.0,...,1.0,2148.0,43.026536,43.0,2.201608e+07,18461600.0,NaN,NaN,165006160.0,42.56
2564,강원도,76,20192,956,3.122340,2.0,173.353562,46.0,1.250000,1.0,...,1.0,2148.0,43.026536,43.0,2.201608e+07,18461600.0,NaN,NaN,165006160.0,42.56
3817,강원도,76,20193,985,3.203125,2.0,172.934211,46.0,1.218750,1.0,...,1.0,2148.0,43.026536,43.0,2.201608e+07,18461600.0,NaN,NaN,165006160.0,46.00
5071,강원도,76,20194,1007,3.106599,2.0,167.070156,43.0,1.091371,1.0,...,1.0,2148.0,43.026536,43.0,2.201608e+07,18461600.0,NaN,NaN,165006160.0,46.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24961,충청북도,76,20233,813,9.635338,3.0,1301.696165,114.0,2.466165,1.0,...,1.0,3051.0,44.520813,44.0,3.146038e+07,26408760.0,NaN,NaN,175829520.0,48.13
26209,충청북도,76,20234,823,9.568773,2.0,1258.405941,111.0,2.386617,1.0,...,1.0,3051.0,44.520813,44.0,3.146038e+07,26408760.0,NaN,NaN,175829520.0,48.13
27457,충청북도,76,20241,790,9.142336,2.0,1372.875362,119.0,2.160584,1.0,...,1.0,3051.0,44.520813,44.0,3.146038e+07,26408760.0,NaN,NaN,175829520.0,59.46
28705,충청북도,76,20242,805,9.236162,2.0,1367.301153,119.5,2.169742,1.0,...,1.0,3051.0,44.520813,44.0,3.146038e+07,26408760.0,NaN,NaN,175829520.0,59.46
29953,충청북도,76,20243,823,8.953069,2.0,1370.372294,120.0,2.025271,1.0,...,1.0,3051.0,44.520813,44.0,3.146038e+07,26408760.0,NaN,NaN,175829520.0,59.46

In [ ]:
# 1. 기준값 추출 (68번 산업)
ref_df = df_merged[
    (df_merged['industry_code'] == 68) &
    df_merged['output_index'].notna() &
    df_merged['labor_productivity_index'].notna()
][['sido', 'base_year_x', 'output_index', 'labor_productivity_index']].copy()

ref_df = ref_df.rename(columns={
    'output_index': 'ref_output_index',
    'labor_productivity_index': 'ref_labor_productivity_index'
})

# 2. 76번 산업 중 결측행 추출
target_idx = df_merged[
    (df_merged['industry_code'] == 76) &
    (df_merged['output_index'].isna() | df_merged['labor_productivity_index'].isna())
].index

target_df = df_merged.loc[target_idx].copy()
target_df['original_index'] = target_df.index  # 인덱스 보존

# 3. merge 후 ref값 가져오기
target_df = target_df.merge(ref_df, on=['sido', 'base_year_x'], how='left')

# 4. 다시 인덱스를 원래 위치로
target_df = target_df.set_index('original_index')

# 5. 원본에 반영 (이제 인덱스 맞음)
df_merged.loc[target_df.index, 'output_index'] = df_merged.loc[target_df.index, 'output_index'].combine_first(target_df['ref_output_index'])
df_merged.loc[target_df.index, 'labor_productivity_index'] = df_merged.loc[target_df.index, 'labor_productivity_index'].combine_first(target_df['ref_labor_productivity_index'])

In [ ]:
# industry_code == 76에서 아직 결측값이 남아 있는 행 수 확인
remaining_nulls = df_merged[
    (df_merged['industry_code'] == 76) &
    (df_merged['output_index'].isna() | df_merged['labor_productivity_index'].isna())
]

print(f"⛔ 아직 채워지지 않은 76번 결측값 수: {len(remaining_nulls)}")

⛔ 아직 채워지지 않은 76번 결측값 수: 0

In [ ]:
# CSV로 저장
df_merged.to_csv('final.csv', index=False, encoding='utf-8-sig')